"""Initial migration

Revision ID: 0280b7956bdd
Revises: 
Create Date: 2024-10-15 12:55:57.466290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0280b7956bdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plots', 'area_sqm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('plots_geom_idx', table_name='plots', postgresql_using='gist')
    op.drop_constraint('plots_plot_number_key', 'plots', type_='unique')
    op.create_unique_constraint(op.f('uq_plots_plot_number'), 'plots', ['plot_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_plots_plot_number'), 'plots', type_='unique')
    op.create_unique_constraint('plots_plot_number_key', 'plots', ['plot_number'])
    op.create_index('plots_geom_idx', 'plots', ['geom'], unique=False, postgresql_using='gist')
    op.alter_column('plots', 'area_sqm',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
