"""Add land_use, development_status, and additional_info columns

Revision ID: 304cffc9664f
Revises: 0280b7956bdd
Create Date: 2024-10-16 16:01:53.185516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304cffc9664f'
down_revision = '0280b7956bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('land_use', sa.String(length=100), nullable=True))
    op.add_column('plots', sa.Column('development_status', sa.String(length=100), nullable=True))
    op.add_column('plots', sa.Column('additional_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plots', 'additional_info')
    op.drop_column('plots', 'development_status')
    op.drop_column('plots', 'land_use')
    # ### end Alembic commands ###
